-- Run this SQL in the Supabase SQL editor before using the app.
-- It keeps auth in Supabase Auth and stores app-specific user data in profiles.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null,
  nickname text not null,
  favorite_genres text[] not null default array['romance', 'fantasy'],
  liked_webtoon_ids text[] not null default '{}',
  mood_logs jsonb not null default '[]'::jsonb,
  liked_comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format
    check (username ~ '^[a-z0-9_]{4,20}$')
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists profiles_username_idx on public.profiles (username);

alter table public.profiles enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_username text;
  profile_nickname text;
  profile_favorite_genres text[];
begin
  profile_username := lower(coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)));
  profile_nickname := coalesce(new.raw_user_meta_data->>'nickname', profile_username);

  select coalesce(array_agg(genres.value), array['romance', 'fantasy'])
  into profile_favorite_genres
  from jsonb_array_elements_text(
    coalesce(new.raw_user_meta_data->'favoriteGenres', '["romance", "fantasy"]'::jsonb)
  ) as genres(value);

  insert into public.profiles (
    id,
    username,
    email,
    nickname,
    favorite_genres
  )
  values (
    new.id,
    profile_username,
    lower(new.email),
    profile_nickname,
    profile_favorite_genres
  )
  on conflict (id) do update set
    username = excluded.username,
    email = excluded.email,
    nickname = excluded.nickname;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.find_profile_by_username(p_username text)
returns table(username text, email text)
language sql
security definer
set search_path = public
as $$
  select profiles.username, profiles.email
  from public.profiles
  where profiles.username = lower(trim(p_username))
  limit 1;
$$;

create or replace function public.find_usernames_by_email(p_email text)
returns table(username text)
language sql
security definer
set search_path = public
as $$
  select profiles.username
  from public.profiles
  where profiles.email = lower(trim(p_email))
  order by profiles.created_at asc;
$$;

grant execute on function public.find_profile_by_username(text) to anon, authenticated;
grant execute on function public.find_usernames_by_email(text) to anon, authenticated;

create or replace function public.get_popular_bookmarked_webtoons(p_limit integer default 4)
returns table(webtoon_id text, bookmark_count integer)
language sql
security definer
set search_path = public
as $$
  select bookmarked.webtoon_id, count(*)::integer as bookmark_count
  from public.profiles
  cross join unnest(profiles.liked_webtoon_ids) as bookmarked(webtoon_id)
  where bookmarked.webtoon_id is not null
    and bookmarked.webtoon_id <> ''
  group by bookmarked.webtoon_id
  order by count(*) desc, bookmarked.webtoon_id asc
  limit greatest(1, least(coalesce(p_limit, 4), 12));
$$;

grant execute on function public.get_popular_bookmarked_webtoons(integer) to anon, authenticated;

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  webtoon_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  text text not null,
  empathy_count integer not null default 0 check (empathy_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_webtoon_id_idx
on public.comments (webtoon_id, created_at desc);

create index if not exists comments_user_id_idx
on public.comments (user_id, created_at desc);

alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments
for select
to anon, authenticated
using (true);

drop policy if exists "Users can create own comments" on public.comments;
create policy "Users can create own comments"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own comments" on public.comments;
create policy "Users can update own comments"
on public.comments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own comments" on public.comments;
create policy "Users can delete own comments"
on public.comments
for delete
to authenticated
using (auth.uid() = user_id);

drop trigger if exists set_comments_updated_at on public.comments;
create trigger set_comments_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create index if not exists comment_likes_user_id_idx
on public.comment_likes (user_id, created_at desc);

alter table public.comment_likes enable row level security;

drop policy if exists "Users can read own comment likes" on public.comment_likes;
create policy "Users can read own comment likes"
on public.comment_likes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own comment likes" on public.comment_likes;
create policy "Users can create own comment likes"
on public.comment_likes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own comment likes" on public.comment_likes;
create policy "Users can delete own comment likes"
on public.comment_likes
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.toggle_comment_like(p_comment_id bigint)
returns table(
  comment_id bigint,
  liked boolean,
  empathy_count integer,
  liked_comment_ids jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  next_liked boolean;
  next_count integer;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if exists (
    select 1
    from public.comment_likes
    where comment_likes.comment_id = p_comment_id
      and comment_likes.user_id = current_user_id
  ) then
    delete from public.comment_likes
    where comment_likes.comment_id = p_comment_id
      and comment_likes.user_id = current_user_id;

    update public.comments as c
    set empathy_count = greatest(c.empathy_count - 1, 0)
    where c.id = p_comment_id
    returning c.empathy_count into next_count;

    next_liked := false;
  else
    insert into public.comment_likes (comment_id, user_id)
    values (p_comment_id, current_user_id);

    update public.comments as c
    set empathy_count = c.empathy_count + 1
    where c.id = p_comment_id
    returning c.empathy_count into next_count;

    next_liked := true;
  end if;

  update public.profiles
  set liked_comments = coalesce(
    (
      select jsonb_agg(comment_likes.comment_id order by comment_likes.created_at desc)
      from public.comment_likes
      where comment_likes.user_id = current_user_id
    ),
    '[]'::jsonb
  )
  where profiles.id = current_user_id
  returning profiles.liked_comments into liked_comment_ids;

  return query
  select p_comment_id, next_liked, next_count, liked_comment_ids;
end;
$$;

grant execute on function public.toggle_comment_like(bigint) to authenticated;
